import type { Metadata } from 'next';
import { Noto_Sans_TC } from 'next/font/google';
import 'normalize.css';
import StyledComponentsRegistry from '../lib/StyledComponentsRegistry';
import GlobalStyle from '../lib/GlobalStyle';

const notoSansTC = Noto_Sans_TC({
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={notoSansTC.className}>
        <StyledComponentsRegistry>
          <GlobalStyle />
          {children}
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
